default_platform(:ios)

platform :ios do
  desc "Upload IPA to TestFlight using App Store Connect API key"
  lane :beta do
    api_key = {
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: 'ios/appstore_connect_key.p8'
    }

    upload_to_testflight(api_key: api_key)
  end

  desc "Deliver to App Store (release)"
  lane :release do
    api_key = {
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: 'ios/appstore_connect_key.p8'
    }

    deliver(api_key: api_key)
  end
end
